/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2016-01-13 16:35:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.cms.WEB_002dINF.field;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.psddev.cms.db.Content;
import com.psddev.cms.db.ToolUi;
import com.psddev.cms.tool.ToolPageContext;
import com.psddev.dari.db.ObjectField;
import com.psddev.dari.db.ObjectFieldComparator;
import com.psddev.dari.db.State;
import com.psddev.dari.db.ObjectType;
import com.psddev.dari.db.Query;
import com.psddev.dari.util.ObjectUtils;
import com.psddev.dari.util.PaginatedResult;
import com.psddev.dari.util.Settings;
import com.psddev.dari.util.StorageItem;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.UUID;

public final class record_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;



// --- Logic ---

ToolPageContext wp = new ToolPageContext(pageContext);

State state = State.getInstance(request.getAttribute("object"));

ObjectField field = (ObjectField) request.getAttribute("field");
String fieldName = field.getInternalName();
Object fieldValue = state.getValue(fieldName);
boolean fieldValueNew = false;

ObjectType fieldValueType = null;
List<ObjectType> validTypes = field.as(ToolUi.class).findDisplayTypes();
if (validTypes.size() == 1) {
    for (ObjectType type : validTypes) {
        fieldValueType = type;
        break;
    }
}

boolean isEmbedded = field.isEmbedded() || (fieldValueType != null && fieldValueType.isEmbedded());
if (!isEmbedded) {
    isEmbedded = true;
    for (ObjectType type : validTypes) {
        if (!type.isEmbedded()) {
            isEmbedded = false;
            break;
        }
    }
}

String inputName = (String) request.getAttribute("inputName");
String setName = inputName + ".setName";
String idName = inputName + ".id";
String typeIdName = inputName + ".typeId";
String publishDateName = inputName + ".publishDate";

UUID id = wp.uuidParam(idName);
UUID typeId = wp.uuidParam(typeIdName);
Date publishDate = wp.dateParam(publishDateName);

if ((Boolean) request.getAttribute("isFormPost") && fieldValue != null && !State.getInstance(fieldValue).getTypeId().equals(typeId)) {
    fieldValue = null;
}

if (fieldValue == null && isEmbedded) {
    if (fieldValueType != null) {
        fieldValue = fieldValueType.createObject(null);
        State.getInstance(fieldValue).setResolveInvisible(true);
        fieldValueNew = true;

    } else {
        for (ObjectType type : validTypes) {
            if (type.getId().equals(typeId)) {
                fieldValue = type.createObject(null);
                State.getInstance(fieldValue).setResolveInvisible(true);
                break;
            }
        }
    }
}

if ((Boolean) request.getAttribute("isFormPost")) {
    if (isEmbedded) {
        if (fieldValue != null && id == null) {
            fieldValue = null;
        }

        if (fieldValue != null) {
            State fieldValueState = State.getInstance(fieldValue);
            fieldValueState.setId(id);
            wp.updateUsingParameters(fieldValue);
            fieldValueState.remove(Content.PUBLISH_DATE_FIELD);
            fieldValueState.remove(Content.UPDATE_DATE_FIELD);

            if (field.isEmbedded() && !fieldValueState.isNew()) {
                fieldValueState.setId(null);
                fieldValueState.setStatus(null);
            }
        }
    } else {
        fieldValue = Query.fromAll().where("_id = ?", wp.uuidParam(inputName)).resolveInvisible().first();
    }

    if ("none".equals(wp.param(String.class, setName))) {
        state.putValue(fieldName, null);

    } else {
        state.putValue(fieldName, fieldValue);
    }

    return;
}

// --- Presentation ---

if (isEmbedded) {
    if (fieldValueType != null) {
        State fieldValueState = State.getInstance(fieldValue);
        Date fieldValuePublishDate = fieldValueState.as(Content.ObjectModification.class).getPublishDate();

        if (!field.isRequired() && !Settings.get(boolean.class, "cms/tool/embeddedObjectRequired")) {
            wp.writeStart("div", "class", "inputSmall");
                wp.writeStart("select",
                        "class", "toggleable",
                        "name", setName,
                        "data-root", ".inputContainer");
                    wp.writeStart("option",
                            "value", "none",
                            "data-hide", "> .inputLarge",
                            "selected", fieldValueNew ? "selected" : null);
                        wp.writeHtmlOrDefault(field.as(ToolUi.class).getPlaceholder(), "None");
                    wp.writeEnd();

                    wp.writeStart("option",
                            "value", "",
                            "data-show", "> .inputLarge",
                            "selected", fieldValueNew ? null : "selected");
                        wp.writeHtml("Set:");
                    wp.writeEnd();
                wp.writeEnd();
            wp.writeEnd();
        }

        wp.write("<div class=\"inputLarge\" data-generic-arguments=\"");

        List<ObjectType> genericArguments = field.getGenericArguments();

        if (genericArguments != null && !genericArguments.isEmpty()) {
            for (Iterator<ObjectType> i = genericArguments.iterator(); i.hasNext();) {
                ObjectType type = i.next();

                wp.write(type.getId());

                if (i.hasNext()) {
                    wp.write(",");
                }
            }
        }

        wp.write("\">");
        wp.write("<input name=\"", wp.h(idName), "\" type=\"hidden\" value=\"", fieldValueState.getId(), "\">");
        wp.write("<input name=\"", wp.h(typeIdName), "\" type=\"hidden\" value=\"", fieldValueState.getTypeId(), "\">");
        wp.write("<input name=\"", wp.h(publishDateName), "\" type=\"hidden\" value=\"", wp.h(fieldValuePublishDate != null ? fieldValuePublishDate.getTime() : null), "\">");
        wp.writeFormFields(fieldValue);
        wp.write("</div>");

    } else {
        List<Object> validObjects = new ArrayList<Object>();
        for (ObjectType type : validTypes) {
            if (fieldValue != null && type.equals(State.getInstance(fieldValue).getType())) {
                validObjects.add(fieldValue);
            } else {
                Object itemObj = type.createObject(null);
                State.getInstance(itemObj).setResolveInvisible(true);
                validObjects.add(itemObj);
            }
        }

        Collections.sort(validObjects, new ObjectFieldComparator("_type/_label", false));

        String validObjectClass = wp.createId();
        Map<UUID, String> showClasses = new HashMap<UUID, String>();
        wp.write("<div class=\"inputSmall\">");
        wp.write("<select class=\"toggleable\" name=\"", wp.h(idName), "\">");

        if (!field.isRequired()) {
            wp.write("<option data-hide=\".", validObjectClass, "\" value=\"\">");
            wp.writeHtmlOrDefault(field.as(ToolUi.class).getPlaceholder(), "None");
            wp.write("</option>");
        }

        for (Object validObject : validObjects) {
            State validState = State.getInstance(validObject);
            String showClass = wp.createId();
            showClasses.put(validState.getId(), showClass);
            wp.write("<option data-hide=\".", validObjectClass, "\" data-show=\".", showClass, "\" value=\"", validState.getId(), "\"");
            if (validObject.equals(fieldValue)) {
                wp.write(" selected");
            }
            wp.write(">");
            wp.write(wp.objectLabel(validState.getType()));
            wp.write("</option>");
        }
        wp.write("</select>");
        wp.write("</div>");

        for (Object validObject : validObjects) {
            State validState = State.getInstance(validObject);
            Date validObjectPublishDate = validState.as(Content.ObjectModification.class).getPublishDate();
            wp.write("<div class=\"inputLarge ", validObjectClass, " ", showClasses.get(validState.getId()), "\">");
            wp.write("<input name=\"", wp.h(typeIdName), "\" type=\"hidden\" value=\"", validState.getTypeId(), "\">");
            wp.write("<input name=\"", wp.h(publishDateName), "\" type=\"hidden\" value=\"", wp.h(validObjectPublishDate != null ? validObjectPublishDate.getTime() : null), "\">");
            if (!validState.hasAnyErrors()) {
                wp.writeStart("div",
                        "class", "toggleable-form",
                        "data-form-fields-data", ObjectUtils.toJson(validState.getSimpleValues()),
                        "data-form-fields-url", wp.cmsUrl(
                                "/contentFormFields",
                                "typeId", validState.getTypeId(),
                                "id", validState.getId()));
                wp.writeEnd();
            } else {
                wp.writeFormFields(validObject);
            }
            wp.write("</div>");
        }
    }

    return;
}


      out.write("<div class=\"inputSmall\">\n");
      out.write("    ");
 wp.writeObjectSelect(field, fieldValue, "name", inputName); 
      out.write("\n");
      out.write("</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
