/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2016-01-13 16:35:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.cms.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.psddev.cms.db.ReferentialTextMarker;
import com.psddev.cms.db.StandardImageSize;
import com.psddev.cms.tool.Area;
import com.psddev.cms.tool.Tool;
import com.psddev.cms.tool.ToolPageContext;
import com.psddev.cms.tool.Widget;
import com.psddev.dari.db.Application;
import com.psddev.dari.db.ObjectType;
import com.psddev.dari.db.Query;
import com.psddev.dari.db.State;
import com.psddev.dari.db.WebResourceOverride;
import java.util.Arrays;
import java.util.List;

public final class settings_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;



// --- Logic ---

ToolPageContext wp = new ToolPageContext(pageContext);
if (wp.requirePermission("area/admin/adminSettings")) {
    return;
}

Object selected = Query.findById(Object.class, wp.uuidParam("id"));
if (selected == null) {
    if (wp.uuidParam("typeId") != null) {
        selected = wp.findOrReserve(StandardImageSize.class);
    } else {
        selected = wp.getCmsTool();
    }
}

if (selected != null && wp.tryStandardUpdate(selected)) {
    return;
}

State selectedState = State.getInstance(selected);
List<StandardImageSize> standardImageSizes = Query.from(StandardImageSize.class).sortAscending("displayName").select();

// --- Presentation ---


 wp.include("/WEB-INF/header.jsp"); 
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"withLeftNav\">\n");
      out.write("    <div class=\"leftNav\">\n");
      out.write("\n");
      out.write("        <div class=\"widget\">\n");
      out.write("            <h1 class=\"icon icon-cogs\">\n");
      out.write("                ");
      out.print( wp.h(wp.localize("com.psddev.cms.tool.page.admin.Settings", "title")));
      out.write("\n");
      out.write("            </h1>\n");
      out.write("\n");
      out.write("            <h2>\n");
      out.write("                ");
      out.print( wp.h(wp.localize("com.psddev.cms.tool.page.admin.Settings", "subtitle.applications")));
      out.write("\n");
      out.write("            </h2>\n");
      out.write("            <ul class=\"links\">\n");
      out.write("                ");
 for (Object app : Query
                        .from(Application.class)
                        .sortAscending("name")
                        .select()) { 
      out.write("\n");
      out.write("                    <li");
      out.print( app.equals(selected) ? " class=\"selected\"" : "" );
      out.write(">\n");
      out.write("                        <a href=\"");
      out.print( wp.objectUrl(null, app) );
      out.write('"');
      out.write('>');
      out.print( wp.objectLabel(app) );
      out.write("</a>\n");
      out.write("                    </li>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("            <h2>\n");
      out.write("                ");
      out.print( wp.h(wp.localize("com.psddev.cms.tool.page.admin.Settings", "subtitle.imageSizes")));
      out.write("\n");
      out.write("            </h2>\n");
      out.write("            <ul class=\"links\">\n");
      out.write("                <li class=\"new");
      out.print( selected instanceof StandardImageSize && selectedState.isNew() ? " selected" : "" );
      out.write("\">\n");
      out.write("                    <a href=\"");
      out.print( wp.typeUrl(null, StandardImageSize.class) );
      out.write("\">\n");
      out.write("                        ");
      out.print( wp.h(wp.localize(StandardImageSize.class, "action.newType")));
      out.write("\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                ");
 for (StandardImageSize size : standardImageSizes) { 
      out.write("\n");
      out.write("                    <li");
      out.print( size.equals(selected) ? " class=\"selected\"" : "" );
      out.write(">\n");
      out.write("                        <a href=\"");
      out.print( wp.objectUrl(null, size) );
      out.write('"');
      out.write('>');
      out.print( wp.objectLabel(size) );
      out.write("</a>\n");
      out.write("                    </li>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("            <h2>\n");
      out.write("                ");
      out.print( wp.h(wp.localize("com.psddev.cms.tool.page.admin.Settings", "subtitle.refTextMarkers")));
      out.write("\n");
      out.write("            </h2>\n");
      out.write("            <ul class=\"links\">\n");
      out.write("                <li class=\"new");
      out.print( selected instanceof ReferentialTextMarker && selectedState.isNew() ? " selected" : "" );
      out.write("\">\n");
      out.write("                    <a href=\"");
      out.print( wp.typeUrl(null, ReferentialTextMarker.class) );
      out.write("\">\n");
      out.write("                        ");
      out.print( wp.h(wp.localize(ReferentialTextMarker.class, "action.newType")));
      out.write("\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                ");
 for (ReferentialTextMarker marker : Query.
                        from(ReferentialTextMarker.class).
                        sortAscending("displayName").
                        select()) { 
      out.write("\n");
      out.write("                    <li");
      out.print( marker.equals(selected) ? " class=\"selected\"" : "" );
      out.write(">\n");
      out.write("                        <a href=\"");
      out.print( wp.objectUrl(null, marker) );
      out.write('"');
      out.write('>');
      out.print( wp.objectLabel(marker) );
      out.write("</a>\n");
      out.write("                    </li>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("            <h2>\n");
      out.write("                ");
      out.print( wp.h(wp.localize("com.psddev.cms.tool.page.admin.Settings", "subtitle.webResourceOverrides")));
      out.write("\n");
      out.write("            </h2>\n");
      out.write("            <ul class=\"links\">\n");
      out.write("                <li class=\"new");
      out.print( selected instanceof WebResourceOverride && selectedState.isNew() ? " selected" : "" );
      out.write("\">\n");
      out.write("                    <a href=\"");
      out.print( wp.typeUrl(null, WebResourceOverride.class) );
      out.write("\">\n");
      out.write("                        ");
      out.print( wp.h(wp.localize(WebResourceOverride.class, "action.newType")));
      out.write("\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                ");
 for (WebResourceOverride override : Query.
                        from(WebResourceOverride.class).
                        sortAscending("path").
                        selectAll()) { 
      out.write("\n");
      out.write("                    <li");
      out.print( override.equals(selected) ? " class=\"selected\"" : "" );
      out.write(">\n");
      out.write("                        <a href=\"");
      out.print( wp.objectUrl(null, override) );
      out.write('"');
      out.write('>');
      out.print( wp.objectLabel(override) );
      out.write("</a>\n");
      out.write("                    </li>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <div class=\"main\">\n");
      out.write("\n");
      out.write("        ");
 if (selected != null) { 
      out.write("\n");
      out.write("            <div class=\"widget\">\n");
      out.write("                ");
 wp.writeStandardForm(selected); 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
 wp.include("/WEB-INF/footer.jsp"); 
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
