/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2016-01-13 18:34:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.cms.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.psddev.cms.db.Site;
import com.psddev.cms.tool.ToolPageContext;
import com.psddev.dari.db.Query;
import com.psddev.dari.db.State;
import java.util.UUID;

public final class sites_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;



// --- Logic ---

ToolPageContext wp = new ToolPageContext(pageContext);
if (wp.requirePermission("area/admin/adminSites")) {
    return;
}

String queryString = wp.param("query");
Object selected = wp.findOrReserve(Site.class);
State selectedState = State.getInstance(selected);
if (wp.tryStandardUpdate(selected)) {
    return;
}

// --- Presentation ---


 wp.include("/WEB-INF/header.jsp"); 
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"withLeftNav\">\n");
      out.write("    <div class=\"leftNav\">\n");
      out.write("        <div class=\"widget\">\n");
      out.write("\n");
      out.write("            <h1 class=\"icon icon-object-site\">\n");
      out.write("                ");
      out.print( wp.h(wp.localize("com.psddev.cms.tool.page.admin.Sites", "title")));
      out.write("\n");
      out.write("            </h1>\n");
      out.write("            <ul class=\"links\">\n");
      out.write("                <li class=\"new");
      out.print( selectedState.isNew() ? " selected" : "" );
      out.write("\">\n");
      out.write("                    <a href=\"");
      out.print( wp.url(null) );
      out.write('"');
      out.write('>');
      out.print( wp.h(wp.localize(Site.class, "action.newType")) );
      out.write("</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("            <form action=\"");
      out.print( wp.url("/admin/sitesResult.jsp") );
      out.write("\" data-bsp-autosubmit=\"\" method=\"get\" target=\"sitesResult\">\n");
      out.write("                <input name=\"id\" type=\"hidden\" value=\"");
      out.print( selectedState.getId() );
      out.write("\">\n");
      out.write("                <div class=\"searchInput\">\n");
      out.write("                    <label for=\"");
      out.print( wp.createId() );
      out.write("\">\n");
      out.write("                        ");
      out.print( wp.h(wp.localize("com.psddev.cms.tool.page.admin.Sites", "label.search")));
      out.write("\n");
      out.write("                    </label>\n");
      out.write("                    <input id=\"");
      out.print( wp.getId() );
      out.write("\" class=\"autoFocus\" name=\"query\" type=\"text\" value=\"");
      out.print( wp.h(queryString) );
      out.write("\">\n");
      out.write("                    <input type=\"submit\" value=\"");
      out.print( wp.h(wp.localize("com.psddev.cms.tool.page.admin.Sites", "action.go")));
      out.write("\">\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <div class=\"frame\" name=\"sitesResult\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"main\">\n");
      out.write("        <div class=\"widget\">\n");
      out.write("\n");
      out.write("            ");
 wp.writeStandardForm(selected); 
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
 wp.include("/WEB-INF/footer.jsp"); 
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
