/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2016-01-13 18:34:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.cms.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.psddev.cms.db.Site;
import com.psddev.cms.tool.ToolPageContext;
import com.psddev.dari.db.Query;
import com.psddev.dari.util.ObjectUtils;
import java.util.Iterator;
import java.util.List;

public final class sitesResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;



// --- Logic ---

ToolPageContext wp = new ToolPageContext(pageContext);
if (wp.requirePermission("area/admin/adminSites")) {
    return;
}

Site selected = (Site) wp.findOrReserve(Site.class);

Query<Site> query = Query.from(Site.class).sortAscending("name");
String queryString = wp.param("query");
if (!ObjectUtils.isBlank(queryString)) {
    query.where("name ^=[c] ?", queryString);
}

List<Site> sites = query.selectAll();
for (Iterator<Site> i = sites.iterator(); i.hasNext(); ) {
    if (!wp.hasPermission(i.next().getPermissionId())) {
        i.remove();
    }
}

// --- Presentation ---


 wp.include("/WEB-INF/header.jsp"); 
      out.write('\n');
      out.write('\n');
 if (!sites.isEmpty()) { 
      out.write("\n");
      out.write("    <ul class=\"links\">\n");
      out.write("        ");
 for (Site site : sites) { 
      out.write("\n");
      out.write("            <li");
      out.print( site.equals(selected) ? " class=\"selected\"" : "" );
      out.write(">\n");
      out.write("                <a href=\"");
      out.print( wp.objectUrl("/admin/sites.jsp", site) );
      out.write("\" target=\"_top\">");
      out.print( wp.objectLabel(site) );
      out.write("</a>\n");
      out.write("            </li>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </ul>\n");
      out.write("\n");
 } else { 
      out.write("\n");
      out.write("    <div class=\"message message-warning\">\n");
      out.write("        <p>\n");
      out.write("            ");
      out.print( wp.h(wp.localize("com.psddev.cms.tool.page.admin.SitesResult", "message.noMatches")));
      out.write("\n");
      out.write("        </p>\n");
      out.write("    </div>\n");
 } 
      out.write('\n');
      out.write('\n');
 wp.include("/WEB-INF/footer.jsp"); 
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
